// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaChotaExpress.Data;

#nullable disable

namespace SistemaChotaExpress.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911220215_AddTurnoSalidaEncomienda")]
    partial class AddTurnoSalidaEncomienda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaChotaExpress.Models.Bus", b =>
                {
                    b.Property<int>("Id_Bus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Bus"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreConductor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreVehiculo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Placa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_Bus");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id_Bus = 1,
                            Capacidad = 15,
                            Modelo = "Toyota HiAce (Combi)",
                            NombreConductor = "Juan Pérez",
                            NombreVehiculo = "Combi 01",
                            Placa = "S/P"
                        },
                        new
                        {
                            Id_Bus = 2,
                            Capacidad = 15,
                            Modelo = "Hyundai H350",
                            NombreConductor = "Carlos Gómez",
                            NombreVehiculo = "Combi 02",
                            Placa = "S/P"
                        },
                        new
                        {
                            Id_Bus = 3,
                            Capacidad = 15,
                            Modelo = "Toyota HiAce (Combi)",
                            NombreConductor = "Mario Silva",
                            NombreVehiculo = "Combi 03",
                            Placa = "S/P"
                        },
                        new
                        {
                            Id_Bus = 4,
                            Capacidad = 15,
                            Modelo = "Mercedes-Benz Sprinter",
                            NombreConductor = "Luis Fernández",
                            NombreVehiculo = "Combi 04",
                            Placa = "S/P"
                        });
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Encomienda", b =>
                {
                    b.Property<int>("Id_Encomienda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Encomienda"));

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DniDestinatario")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("DniRemitente")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Id_Ruta")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreRemitente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("PrecioEnvio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TelefonoDestinatario")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TelefonoRemitente")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TurnoSalida")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_Encomienda");

                    b.HasIndex("Id_Ruta");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Encomiendas");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Pasajero", b =>
                {
                    b.Property<int>("Id_Pasajero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pasajero"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id_Pasajero");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Roles", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id_Rol = 1,
                            NombreRol = "Gerente"
                        },
                        new
                        {
                            Id_Rol = 2,
                            NombreRol = "Vendedor"
                        });
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Ruta", b =>
                {
                    b.Property<int>("Id_Ruta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ruta"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("DuracionHoras")
                        .HasColumnType("double precision");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_Ruta");

                    b.ToTable("Rutas");

                    b.HasData(
                        new
                        {
                            Id_Ruta = 1,
                            Destino = "Chota",
                            DuracionHoras = 6.0,
                            Origen = "Chiclayo"
                        },
                        new
                        {
                            Id_Ruta = 2,
                            Destino = "Chiclayo",
                            DuracionHoras = 6.0,
                            Origen = "Chota"
                        },
                        new
                        {
                            Id_Ruta = 3,
                            Destino = "Chota",
                            DuracionHoras = 4.0,
                            Origen = "Cajamarca"
                        },
                        new
                        {
                            Id_Ruta = 4,
                            Destino = "Cajamarca",
                            DuracionHoras = 4.0,
                            Origen = "Chota"
                        },
                        new
                        {
                            Id_Ruta = 5,
                            Destino = "Chiclayo",
                            DuracionHoras = 7.0,
                            Origen = "Cajamarca"
                        },
                        new
                        {
                            Id_Ruta = 6,
                            Destino = "Cajamarca",
                            DuracionHoras = 7.0,
                            Origen = "Chiclayo"
                        },
                        new
                        {
                            Id_Ruta = 7,
                            Destino = "Chota",
                            DuracionHoras = 1.5,
                            Origen = "Bambamarca"
                        },
                        new
                        {
                            Id_Ruta = 8,
                            Destino = "Bambamarca",
                            DuracionHoras = 1.5,
                            Origen = "Chota"
                        },
                        new
                        {
                            Id_Ruta = 9,
                            Destino = "Cutervo",
                            DuracionHoras = 2.0,
                            Origen = "Chota"
                        },
                        new
                        {
                            Id_Ruta = 10,
                            Destino = "Chota",
                            DuracionHoras = 2.0,
                            Origen = "Cutervo"
                        });
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Rol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id_Usuario = 1,
                            Email = "gerente@chotaexpress.com",
                            Id_Rol = 1,
                            Name = "Gerente General",
                            Password = "gerente123",
                            Telefono = "976543210"
                        },
                        new
                        {
                            Id_Usuario = 2,
                            Email = "vendedor@chotaexpress.com",
                            Id_Rol = 2,
                            Name = "Juan Vendedor",
                            Password = "vendedor123",
                            Telefono = "987654321"
                        });
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Venta", b =>
                {
                    b.Property<int>("Id_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Venta"));

                    b.Property<string>("DireccionEmpresa")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_Pasajero")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Viaje")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroAsiento")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("PrecioPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazonSocialEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RucEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id_Venta");

                    b.HasIndex("Id_Pasajero");

                    b.HasIndex("Id_Usuario");

                    b.HasIndex("Id_Viaje");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Viaje", b =>
                {
                    b.Property<int>("Id_Viaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Viaje"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Id_Bus")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Ruta")
                        .HasColumnType("integer");

                    b.Property<string>("NombreConductor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Viaje");

                    b.HasIndex("Id_Bus");

                    b.HasIndex("Id_Ruta");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Encomienda", b =>
                {
                    b.HasOne("SistemaChotaExpress.Models.Ruta", "ObjetoRuta")
                        .WithMany()
                        .HasForeignKey("Id_Ruta");

                    b.HasOne("SistemaChotaExpress.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("Id_Usuario");

                    b.Navigation("ObjetoRuta");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Usuario", b =>
                {
                    b.HasOne("SistemaChotaExpress.Models.Roles", "ObjetoRol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetoRol");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Venta", b =>
                {
                    b.HasOne("SistemaChotaExpress.Models.Pasajero", "ObjetoPasajero")
                        .WithMany()
                        .HasForeignKey("Id_Pasajero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaChotaExpress.Models.Usuario", "ObjetoUsuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaChotaExpress.Models.Viaje", "ObjetoViaje")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_Viaje")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObjetoPasajero");

                    b.Navigation("ObjetoUsuario");

                    b.Navigation("ObjetoViaje");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Viaje", b =>
                {
                    b.HasOne("SistemaChotaExpress.Models.Bus", "ObjetoBus")
                        .WithMany()
                        .HasForeignKey("Id_Bus");

                    b.HasOne("SistemaChotaExpress.Models.Ruta", "ObjetoRuta")
                        .WithMany()
                        .HasForeignKey("Id_Ruta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ObjetoBus");

                    b.Navigation("ObjetoRuta");
                });

            modelBuilder.Entity("SistemaChotaExpress.Models.Viaje", b =>
                {
                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
